# Generated by Django 5.2.13 on 2026-04-26 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='householdmembership',
            name='can_manage_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='householdmembership',
            name='can_post_share',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='householdmembership',
            name='can_upload_receipts',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='HouseholdInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='households.household')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_household_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_household_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('household', 'invited_email'), name='unique_pending_household_invitation')],
            },
        ),
    ]
