# Generated by Django 5.2.13 on 2026-04-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("households", "0003_householdmembership_can_manage_members_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="householdmembership",
            name="can_post_share",
            field=models.BooleanField(default=True),
        ),
    ]
