# Generated by Django 5.2.13 on 2026-04-26 08:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('signup_bonus', 'Signup bonus'), ('locker_purchase_escrow', 'Locker purchase (escrow)'), ('locker_payout_release', 'Locker payout release')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LockerCompartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(choices=[('dry', 'Dry'), ('refrigerated', 'Refrigerated'), ('frozen', 'Frozen')], max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied'), ('out_of_service', 'Out of service')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LockerListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('available', 'Available'), ('sold', 'Sold'), ('picked_up', 'Picked up'), ('cancelled', 'Cancelled')], default='reserved', max_length=20)),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('dropoff_code', models.CharField(blank=True, default='', max_length=6)),
                ('pickup_code', models.CharField(blank=True, default='', max_length=6)),
                ('escrow_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('escrow_released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LockerSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('address_label', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
