# Generated by Django 5.2.13 on 2026-04-26 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('lockers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_tx_out', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_tx_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lockerlisting',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locker_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lockerlisting',
            name='compartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='lockers.lockercompartment'),
        ),
        migrations.AddField(
            model_name='lockerlisting',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locker_listings', to='core.fooditem'),
        ),
        migrations.AddField(
            model_name='lockerlisting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locker_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='lockers.lockerlisting'),
        ),
        migrations.AddField(
            model_name='lockerlisting',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='lockers.lockersite'),
        ),
        migrations.AddField(
            model_name='lockercompartment',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartments', to='lockers.lockersite'),
        ),
        migrations.AddConstraint(
            model_name='lockerlisting',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['reserved', 'available', 'sold'])), fields=('compartment',), name='unique_active_listing_per_compartment'),
        ),
        migrations.AddConstraint(
            model_name='lockercompartment',
            constraint=models.UniqueConstraint(fields=('site', 'label'), name='unique_compartment_label_per_site'),
        ),
    ]
