"""
Local grocery knowledge base for offline item enrichment.
Maps common receipt abbreviations to standardized names, categories, and shelf life.
"""

# Format: "ABBREVIATION_OR_KEYWORD": ("Standardized Name", "category", expiration_days, "description")
GROCERY_DB = {
    # --- Produce: Fruits ---
    "HNYCRSP APPL": ("Honeycrisp Apples", "produce", 21, "Premium sweet-tart apples, great for snacking"),
    "APPL": ("Apples", "produce", 21, "Fresh apples"),
    "APPLE": ("Apples", "produce", 21, "Fresh apples"),
    "BANNAS": ("Bananas", "produce", 5, "Fresh bananas, ripen at room temperature"),
    "BANANA": ("Bananas", "produce", 5, "Fresh bananas, ripen at room temperature"),
    "BANAN": ("Bananas", "produce", 5, "Fresh bananas"),
    "ORG BANNAS": ("Organic Bananas", "produce", 5, "Organic bananas"),
    "STRWBRY": ("Strawberries", "produce", 5, "Fresh strawberries, refrigerate immediately"),
    "STRAWBERR": ("Strawberries", "produce", 5, "Fresh strawberries"),
    "BLUBRY": ("Blueberries", "produce", 7, "Fresh blueberries, rich in antioxidants"),
    "BLUEBRY": ("Blueberries", "produce", 7, "Fresh blueberries"),
    "BLUEBERR": ("Blueberries", "produce", 7, "Fresh blueberries"),
    "RASPBRY": ("Raspberries", "produce", 3, "Fresh raspberries, very perishable"),
    "GRAPES": ("Grapes", "produce", 7, "Fresh grapes"),
    "GRP": ("Grapes", "produce", 7, "Fresh grapes"),
    "AVOCADO": ("Avocados", "produce", 4, "Ripe avocados, refrigerate when ripe"),
    "AVOCDO": ("Avocados", "produce", 4, "Avocados"),
    "AVO": ("Avocados", "produce", 4, "Avocados"),
    "LEMON": ("Lemons", "produce", 21, "Fresh lemons"),
    "LIME": ("Limes", "produce", 14, "Fresh limes"),
    "ORANGE": ("Oranges", "produce", 14, "Fresh oranges"),
    "ORNG": ("Oranges", "produce", 14, "Fresh oranges"),
    "MANGO": ("Mangoes", "produce", 5, "Fresh mangoes"),
    "PEACH": ("Peaches", "produce", 4, "Fresh peaches"),
    "PEAR": ("Pears", "produce", 5, "Fresh pears"),
    "WATERMELON": ("Watermelon", "produce", 7, "Fresh watermelon"),
    "WTRML": ("Watermelon", "produce", 7, "Fresh watermelon"),
    "PINEAPPL": ("Pineapple", "produce", 5, "Fresh pineapple"),
    "CHERR": ("Cherries", "produce", 5, "Fresh cherries"),
    # --- Produce: Vegetables ---
    "BROCCOLI": ("Broccoli", "produce", 5, "Fresh broccoli, store in crisper drawer"),
    "BROCLI": ("Broccoli", "produce", 5, "Fresh broccoli"),
    "SPINACH": ("Spinach", "produce", 5, "Fresh spinach leaves"),
    "SPNCH": ("Spinach", "produce", 5, "Fresh spinach"),
    "LETTUCE": ("Lettuce", "produce", 7, "Fresh lettuce"),
    "ROMAINE": ("Romaine Lettuce", "produce", 7, "Romaine lettuce hearts"),
    "KALE": ("Kale", "produce", 5, "Fresh kale"),
    "CARROT": ("Carrots", "produce", 21, "Fresh carrots"),
    "CRRT": ("Carrots", "produce", 21, "Fresh carrots"),
    "CELERY": ("Celery", "produce", 14, "Fresh celery stalks"),
    "CLRY": ("Celery", "produce", 14, "Fresh celery"),
    "TOMATO": ("Tomatoes", "produce", 7, "Fresh tomatoes"),
    "TMTO": ("Tomatoes", "produce", 7, "Fresh tomatoes"),
    "CUCUMBER": ("Cucumber", "produce", 7, "Fresh cucumber"),
    "CUCMBR": ("Cucumber", "produce", 7, "Fresh cucumber"),
    "ONION": ("Onions", "produce", 30, "Fresh onions, store in cool dry place"),
    "POTATO": ("Potatoes", "produce", 21, "Fresh potatoes"),
    "PTTO": ("Potatoes", "produce", 21, "Fresh potatoes"),
    "SWT PTTO": ("Sweet Potatoes", "produce", 14, "Sweet potatoes"),
    "SWEET POTATO": ("Sweet Potatoes", "produce", 14, "Sweet potatoes"),
    "BELL PEPPER": ("Bell Peppers", "produce", 7, "Fresh bell peppers"),
    "BL PPPR": ("Bell Peppers", "produce", 7, "Fresh bell peppers"),
    "PEPPER": ("Peppers", "produce", 7, "Fresh peppers"),
    "MUSHROOM": ("Mushrooms", "produce", 5, "Fresh mushrooms"),
    "MSHRM": ("Mushrooms", "produce", 5, "Fresh mushrooms"),
    "ZUCCHINI": ("Zucchini", "produce", 5, "Fresh zucchini"),
    "CORN": ("Corn", "produce", 3, "Fresh corn on the cob"),
    "GARLIC": ("Garlic", "produce", 30, "Fresh garlic bulbs"),
    "GINGER": ("Ginger", "produce", 21, "Fresh ginger root"),
    "ASPARAGUS": ("Asparagus", "produce", 4, "Fresh asparagus spears"),
    "GREEN BEAN": ("Green Beans", "produce", 5, "Fresh green beans"),
    "CABBAGE": ("Cabbage", "produce", 14, "Fresh cabbage"),
    "CAULIFLOWER": ("Cauliflower", "produce", 7, "Fresh cauliflower"),
    "CILANTRO": ("Cilantro", "produce", 7, "Fresh cilantro"),
    "BASIL": ("Basil", "produce", 5, "Fresh basil"),
    "JALAPENO": ("Jalapeño Peppers", "produce", 7, "Fresh jalapeño peppers"),
    # --- Dairy ---
    "MLK": ("Milk", "dairy", 10, "Fresh milk, keep refrigerated"),
    "MILK": ("Milk", "dairy", 10, "Fresh milk"),
    "SKM MLK": ("Skim Milk", "dairy", 10, "Fat-free skim milk"),
    "2% MLK": ("2% Milk", "dairy", 10, "Reduced fat 2% milk"),
    "WHL MLK": ("Whole Milk", "dairy", 10, "Whole milk"),
    "OAT MLK": ("Oat Milk", "dairy", 14, "Oat milk, plant-based dairy alternative"),
    "OATMILK": ("Oat Milk", "dairy", 14, "Oat milk"),
    "ALMOND MLK": ("Almond Milk", "dairy", 14, "Almond milk, plant-based"),
    "ALMND MLK": ("Almond Milk", "dairy", 14, "Almond milk"),
    "GRK YGRT": ("Greek Yogurt", "dairy", 14, "Creamy Greek-style yogurt, high in protein"),
    "GREEK YOGURT": ("Greek Yogurt", "dairy", 14, "Greek yogurt"),
    "YOGURT": ("Yogurt", "dairy", 14, "Fresh yogurt"),
    "YGRT": ("Yogurt", "dairy", 14, "Fresh yogurt"),
    "CHEESE": ("Cheese", "dairy", 21, "Cheese"),
    "CHEDDAR": ("Cheddar Cheese", "dairy", 28, "Cheddar cheese"),
    "CHDR CHS": ("Cheddar Cheese", "dairy", 28, "Cheddar cheese"),
    "MOZZARELLA": ("Mozzarella Cheese", "dairy", 14, "Fresh mozzarella cheese"),
    "MOZZ": ("Mozzarella Cheese", "dairy", 14, "Mozzarella cheese"),
    "PARM": ("Parmesan Cheese", "dairy", 42, "Parmesan cheese"),
    "CREAM CHS": ("Cream Cheese", "dairy", 21, "Cream cheese spread"),
    "CREAM CHEESE": ("Cream Cheese", "dairy", 21, "Cream cheese"),
    "SOUR CREAM": ("Sour Cream", "dairy", 14, "Sour cream"),
    "SR CRM": ("Sour Cream", "dairy", 14, "Sour cream"),
    "BUTTER": ("Butter", "dairy", 30, "Butter"),
    "BTTR": ("Butter", "dairy", 30, "Butter"),
    "EGGS": ("Eggs", "dairy", 28, "Fresh eggs"),
    "EGG": ("Eggs", "dairy", 28, "Fresh eggs"),
    "LRG EGGS": ("Large Eggs", "dairy", 28, "Large grade A eggs"),
    "HVY CRM": ("Heavy Cream", "dairy", 14, "Heavy whipping cream"),
    "HEAVY CREAM": ("Heavy Cream", "dairy", 14, "Heavy whipping cream"),
    "HALF HALF": ("Half & Half", "dairy", 10, "Half and half cream"),
    "COTTAGE CHS": ("Cottage Cheese", "dairy", 10, "Cottage cheese"),
    # --- Meat & Seafood ---
    "CHICKEN": ("Chicken", "meat", 3, "Fresh chicken, cook or freeze promptly"),
    "CHKN": ("Chicken", "meat", 3, "Fresh chicken"),
    "CHKN BRST": ("Chicken Breast", "meat", 3, "Boneless chicken breast"),
    "CHICKEN BREAST": ("Chicken Breast", "meat", 3, "Boneless chicken breast"),
    "GROUND BEEF": ("Ground Beef", "meat", 2, "Fresh ground beef, cook or freeze within 2 days"),
    "GRND BF": ("Ground Beef", "meat", 2, "Ground beef"),
    "BEEF": ("Beef", "meat", 3, "Fresh beef"),
    "STEAK": ("Steak", "meat", 3, "Fresh steak"),
    "PORK": ("Pork", "meat", 3, "Fresh pork"),
    "PRK CHP": ("Pork Chops", "meat", 3, "Fresh pork chops"),
    "BACON": ("Bacon", "meat", 7, "Bacon, keep refrigerated"),
    "BCN": ("Bacon", "meat", 7, "Bacon"),
    "SAUSAGE": ("Sausage", "meat", 5, "Fresh sausage"),
    "SAUSG": ("Sausage", "meat", 5, "Fresh sausage"),
    "TURKEY": ("Turkey", "meat", 3, "Fresh turkey"),
    "TRKY": ("Turkey", "meat", 3, "Fresh turkey"),
    "DELI MEAT": ("Deli Meat", "meat", 5, "Sliced deli meat"),
    "HAM": ("Ham", "meat", 5, "Ham"),
    "SALMON": ("Salmon", "meat", 2, "Fresh salmon fillet"),
    "SLMN": ("Salmon", "meat", 2, "Fresh salmon"),
    "SHRIMP": ("Shrimp", "meat", 2, "Fresh shrimp"),
    "SHRMP": ("Shrimp", "meat", 2, "Fresh shrimp"),
    "TILAPIA": ("Tilapia", "meat", 2, "Fresh tilapia fillet"),
    "TUNA": ("Tuna", "meat", 2, "Fresh tuna"),
    # --- Bakery ---
    "BREAD": ("Bread", "bakery", 5, "Fresh bread"),
    "BRD": ("Bread", "bakery", 5, "Fresh bread"),
    "WHL WHT BRD": ("Whole Wheat Bread", "bakery", 5, "Whole wheat bread"),
    "BAGEL": ("Bagels", "bakery", 5, "Fresh bagels"),
    "BGL": ("Bagels", "bakery", 5, "Bagels"),
    "TORTILLA": ("Tortillas", "bakery", 14, "Tortillas"),
    "TRTLA": ("Tortillas", "bakery", 14, "Tortillas"),
    "CROISSANT": ("Croissants", "bakery", 3, "Fresh croissants"),
    "MUFFIN": ("Muffins", "bakery", 3, "Fresh muffins"),
    "ROLL": ("Dinner Rolls", "bakery", 5, "Fresh dinner rolls"),
    "BUNS": ("Hamburger Buns", "bakery", 5, "Hamburger buns"),
    "PITA": ("Pita Bread", "bakery", 7, "Pita bread"),
    # --- Pantry ---
    "RICE": ("Rice", "pantry", 365, "Dry rice"),
    "PASTA": ("Pasta", "pantry", 365, "Dry pasta"),
    "SPGHTI": ("Spaghetti", "pantry", 365, "Spaghetti pasta"),
    "SPAGHETTI": ("Spaghetti", "pantry", 365, "Spaghetti pasta"),
    "PENNE": ("Penne Pasta", "pantry", 365, "Penne pasta"),
    "CEREAL": ("Cereal", "pantry", 180, "Breakfast cereal"),
    "OATMEAL": ("Oatmeal", "pantry", 365, "Oatmeal"),
    "OATS": ("Oats", "pantry", 365, "Rolled oats"),
    "PEANUT BUTTER": ("Peanut Butter", "pantry", 180, "Peanut butter"),
    "PNT BTTR": ("Peanut Butter", "pantry", 180, "Peanut butter"),
    "OLIVE OIL": ("Olive Oil", "pantry", 365, "Extra virgin olive oil"),
    "OLV OIL": ("Olive Oil", "pantry", 365, "Olive oil"),
    "FLOUR": ("Flour", "pantry", 180, "All-purpose flour"),
    "SUGAR": ("Sugar", "pantry", 730, "Granulated sugar"),
    "SALT": ("Salt", "pantry", 1825, "Table salt"),
    "BEANS": ("Beans", "pantry", 365, "Canned or dry beans"),
    "BLK BEANS": ("Black Beans", "pantry", 365, "Black beans"),
    "CANNED TOMATO": ("Canned Tomatoes", "pantry", 365, "Canned tomatoes"),
    "SOUP": ("Soup", "pantry", 365, "Canned soup"),
    "CHIPS": ("Chips", "pantry", 60, "Snack chips"),
    "CRACKERS": ("Crackers", "pantry", 90, "Crackers"),
    "CRCKRS": ("Crackers", "pantry", 90, "Crackers"),
    "GRANOLA": ("Granola", "pantry", 90, "Granola"),
    "NUTS": ("Mixed Nuts", "pantry", 90, "Mixed nuts"),
    "ALMONDS": ("Almonds", "pantry", 90, "Almonds"),
    "HONEY": ("Honey", "pantry", 730, "Honey"),
    "JAM": ("Jam", "pantry", 180, "Fruit jam"),
    "JELLY": ("Jelly", "pantry", 180, "Fruit jelly"),
    "KETCHUP": ("Ketchup", "condiment", 180, "Ketchup"),
    "MUSTARD": ("Mustard", "condiment", 365, "Mustard"),
    "MAYO": ("Mayonnaise", "condiment", 60, "Mayonnaise"),
    "SOY SAUCE": ("Soy Sauce", "condiment", 365, "Soy sauce"),
    "HOT SAUCE": ("Hot Sauce", "condiment", 365, "Hot sauce"),
    "SALSA": ("Salsa", "condiment", 14, "Fresh salsa"),
    # --- Frozen ---
    "FRZN PIZZA": ("Frozen Pizza", "frozen", 180, "Frozen pizza"),
    "FROZEN PIZZA": ("Frozen Pizza", "frozen", 180, "Frozen pizza"),
    "ICE CREAM": ("Ice Cream", "frozen", 60, "Ice cream"),
    "IC CRM": ("Ice Cream", "frozen", 60, "Ice cream"),
    "FRZN VEG": ("Frozen Vegetables", "frozen", 240, "Frozen mixed vegetables"),
    "FROZEN VEG": ("Frozen Vegetables", "frozen", 240, "Frozen vegetables"),
    "FRZN FRUIT": ("Frozen Fruit", "frozen", 240, "Frozen fruit mix"),
    "FRZN CHKN": ("Frozen Chicken", "frozen", 270, "Frozen chicken"),
    "WAFFLES": ("Frozen Waffles", "frozen", 120, "Frozen waffles"),
    "FRZN DINNER": ("Frozen Dinner", "frozen", 120, "Frozen dinner entrée"),
    # --- Beverages ---
    "JUICE": ("Juice", "beverage", 10, "Refrigerated juice"),
    "OJ": ("Orange Juice", "beverage", 10, "Orange juice"),
    "ORNG JCE": ("Orange Juice", "beverage", 10, "Orange juice"),
    "WATER": ("Water", "beverage", 365, "Bottled water"),
    "SODA": ("Soda", "beverage", 180, "Soda"),
    "COFFEE": ("Coffee", "pantry", 180, "Ground coffee"),
    "TEA": ("Tea", "pantry", 365, "Tea bags"),
    # --- Snacks & Deli ---
    "HUMMUS": ("Hummus", "deli", 10, "Fresh hummus"),
    "HMMS": ("Hummus", "deli", 10, "Hummus"),
    "GUACAMOLE": ("Guacamole", "deli", 3, "Fresh guacamole"),
    "GUAC": ("Guacamole", "deli", 3, "Guacamole"),
    "TOFU": ("Tofu", "produce", 7, "Fresh tofu, keep refrigerated"),
}

# Common receipt abbreviations and what they expand to
ABBREVIATION_MAP = {
    "ORG": "ORGANIC", "ORGN": "ORGANIC", "ORGNC": "ORGANIC",
    "MLK": "MILK", "MIK": "MILK",
    "GRK": "GREEK", "GREK": "GREEK",
    "YGRT": "YOGURT", "YGT": "YOGURT", "YOGRT": "YOGURT",
    "BRD": "BREAD",
    "CHS": "CHEESE", "CHSE": "CHEESE",
    "CHKN": "CHICKEN", "CHCK": "CHICKEN", "CHCKN": "CHICKEN",
    "BF": "BEEF",
    "PRK": "PORK",
    "SLMN": "SALMON",
    "SHRMP": "SHRIMP",
    "TRKY": "TURKEY",
    "BTTR": "BUTTER",
    "CRM": "CREAM",
    "BRST": "BREAST",
    "GRND": "GROUND",
    "WHL": "WHOLE",
    "WHT": "WHEAT",
    "SKM": "SKIM",
    "GAL": "GALLON",
    "QT": "QUART",
    "PT": "PINT",
    "OZ": "OUNCE",
    "LB": "POUND",
    "LBS": "POUNDS",
    "PK": "PACK",
    "PKG": "PACKAGE",
    "CT": "COUNT",
    "SM": "SMALL",
    "MD": "MEDIUM",
    "LG": "LARGE",
    "LRG": "LARGE",
    "XL": "EXTRA LARGE",
    "APPL": "APPLE",
    "HNYCRSP": "HONEYCRISP",
    "HNYCR": "HONEYCRISP",
    "STRWBRY": "STRAWBERRY", "STRWB": "STRAWBERRY",
    "BLUBRY": "BLUEBERRY", "BLUBR": "BLUEBERRY",
    "RASPBRY": "RASPBERRY",
    "BANNAS": "BANANAS", "BANAN": "BANANA",
    "CRRT": "CARROT",
    "TMTO": "TOMATO",
    "CLRY": "CELERY",
    "CUCMBR": "CUCUMBER",
    "MSHRM": "MUSHROOM",
    "PPPR": "PEPPER",
    "PTTO": "POTATO",
    "SWT": "SWEET",
    "SPNCH": "SPINACH",
    "BROCLI": "BROCCOLI",
    "AVOCDO": "AVOCADO", "AVO": "AVOCADO",
    "ORNG": "ORANGE",
    "WTRML": "WATERMELON",
    "SPGHTI": "SPAGHETTI",
    "CRCKRS": "CRACKERS",
    "PNT": "PEANUT",
    "OLV": "OLIVE",
    "BCN": "BACON",
    "SAUSG": "SAUSAGE",
    "TRTLA": "TORTILLA",
    "BGL": "BAGEL",
    "HMMS": "HUMMUS",
    "HVY": "HEAVY",
    "FRZN": "FROZEN",
    "JCE": "JUICE",
    "ALMND": "ALMOND",
    "IC": "ICE",
    "VEG": "VEGETABLES",
    "FRT": "FRUIT",
    "SR": "SOUR",
}

# Category-based default expiration when no match found
CATEGORY_DEFAULTS = {
    "produce": 7,
    "dairy": 10,
    "meat": 3,
    "bakery": 5,
    "pantry": 180,
    "frozen": 180,
    "beverage": 14,
    "condiment": 180,
    "deli": 7,
    "unknown": 7,
}

# Keywords that hint at category
CATEGORY_KEYWORDS = {
    "produce": ["apple", "banana", "berry", "grape", "avocado", "lemon", "lime", "orange", "mango",
                 "peach", "pear", "melon", "cherry", "plum", "kiwi", "broccoli", "spinach", "lettuce",
                 "carrot", "celery", "tomato", "cucumber", "onion", "potato", "pepper", "mushroom",
                 "corn", "garlic", "ginger", "asparagus", "bean", "cabbage", "cauliflower", "kale",
                 "zucchini", "cilantro", "basil", "herb", "fruit", "vegetable", "organic", "fresh",
                 "honeycrisp", "romaine", "jalapeño", "jalapeno", "tofu"],
    "dairy": ["milk", "yogurt", "cheese", "cream", "butter", "egg", "sour", "cottage", "mozzarella",
              "cheddar", "parmesan", "half", "whip"],
    "meat": ["chicken", "beef", "pork", "turkey", "bacon", "sausage", "ham", "steak", "salmon",
             "shrimp", "fish", "tilapia", "tuna", "deli", "ground"],
    "bakery": ["bread", "bagel", "tortilla", "croissant", "muffin", "roll", "bun", "pita", "wheat"],
    "pantry": ["rice", "pasta", "cereal", "oat", "peanut", "oil", "flour", "sugar", "salt",
               "bean", "soup", "chip", "cracker", "granola", "nut", "honey", "jam", "jelly",
               "coffee", "tea", "sauce", "canned", "dry", "spaghetti", "penne"],
    "frozen": ["frozen", "ice cream", "waffle", "frzn"],
    "beverage": ["juice", "water", "soda", "drink", "lemonade"],
    "condiment": ["ketchup", "mustard", "mayo", "salsa", "hot sauce", "soy sauce"],
}
