# Generated by Django 5.2.13 on 2026-04-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, default='', max_length=255)),
                ('quantity_label', models.CharField(blank=True, default='', max_length=100)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='share_post_images/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('claimed', 'Claimed')], default='available', max_length=50)),
                ('claimed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
