# Generated by Django 5.2.13 on 2026-04-26 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='claimed_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.fooditem'),
        ),
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postrequest',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requests', to='posts.post'),
        ),
        migrations.AddField(
            model_name='postrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='postrequest',
            constraint=models.UniqueConstraint(fields=('post', 'requester'), name='unique_post_request_per_requester'),
        ),
        migrations.AddConstraint(
            model_name='postrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('post',), name='unique_pending_post_request'),
        ),
        migrations.AddConstraint(
            model_name='postrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('post',), name='unique_approved_post_request'),
        ),
    ]
