# Generated by Django 5.2.13 on 2026-04-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrequest',
            name='dropoff_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='postrequest',
            name='dropoff_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='postrequest',
            name='dropoff_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='postrequest',
            name='fulfillment_method',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Simulated Delivery')], default='pickup', max_length=20),
        ),
    ]
