# Generated by Django 5.2.13 on 2026-04-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='store_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
