# Generated by Django 5.2.13 on 2026-04-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_receipt_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='detected_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
