# Generated by Django 6.0.4 on 2026-04-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
