# Generated by Django 5.2.13 on 2026-04-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactlog',
            name='co2_saved_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='impactlog',
            name='electricity_saved_kwh',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='impactlog',
            name='water_saved_gallons',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
