# Generated by Django 5.2.13 on 2026-04-25 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sharepost_claimed_by_user_sharepost_estimated_price_and_more"),
        ("households", "0004_alter_householdmembership_can_post_share"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_food_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="impactlog",
            name="household",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="impact_logs",
                to="households.household",
            ),
        ),
        migrations.AddField(
            model_name="impactlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="impact_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
